package URLReaderApp;


/**
* URLReaderApp/URLReaderOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from urlreader.idl
* Saturday, 7 May, 2022 4:00:30 PM IST
*/

public interface URLReaderOperations 
{
  int urlbytes (String url);
  void shutdown ();
} // interface URLReaderOperations
