package URLReaderApp;


/**
* URLReaderApp/URLReader.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from urlreader.idl
* Saturday, 7 May, 2022 4:00:30 PM IST
*/

public interface URLReader extends URLReaderOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface URLReader
